### ISSUE TITLE
Quando si crea un augurio mettere la preview in background al posto che come thumbnail in alto

### ISSUE THREAD

**Issue by feroda** [feroda/digitalwishes-ui#1]

**Comment by Radeox** [comment]
![screenshot from 2016-01-02 23-13-54](https://cloud.githubusercontent.com/assets/9751015/12076310/8db38fcc-b1a6-11e5-8133-73335f4cf0f1.png)
Intendevi in background cosi?

**Comment by feroda** [comment]
ottimo lavoro!
