### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by kspin** [feroda/digitalwishes-ui#18]
.. o qualche controllo antispam....

**Comment by feroda** [comment]
di questo abbiamo parlato al telefono. Serve per l'invio diretto della mail.

Per mostrare meno campi all'utente e abbassare il livello di consocenza necessario mettiamo un bottone in piu' "Invia l'augurio ad un amico" che fa apparire i campi necessari (il destinatario e se mantenerlo privato).

Riguardo al captcha la mail verrà inviata solo a seguito dell'approvazione dell'augurio come per gli auguri pubblici

relativo a #2

**Comment by feroda** [comment]
non necessario il captcha perché la mail viene inviata solo post approvazione di un moderatore
