### ISSUE TITLE
Aggiungere pannello partner

### ISSUE THREAD

**Issue by feroda** [feroda/digitalwishes-ui#4]
fabrianodigital, makerspace, fabricamenti, fotografi e sviluppatori

**Comment by feroda** [comment]
Pensavo di prendere la tab "chat" già implementata nella app di prova "tabs". Magari mettiamo i loghi più grandi: FabrianoDigital, Makerspace, Fabricamenti ok? Invece per fotografi e sviluppatori potremmo proprio metterli come il pannello chat

**Comment by Radeox** [comment]
![screenshot from 2015-12-29 20-50-39](https://cloud.githubusercontent.com/assets/9751015/12041008/e0f25790-ae6d-11e5-8e50-c0338482bf34.png)
![screenshot from 2015-12-29 20-51-22](https://cloud.githubusercontent.com/assets/9751015/12041017/f5897526-ae6d-11e5-86b0-ff42556b4a26.png)
![screenshot from 2015-12-29 20-51-26](https://cloud.githubusercontent.com/assets/9751015/12041018/f58f13be-ae6d-11e5-8bd6-4548ac5870d1.png)

Pushato sul fork, funziona ma ce da sistemare eventuali css e ce un piccolo bug: 
se si ricarica la pagina mentre ci si trova sulla pagina partners, quella diventa la "home" e ce il tasto invia auguri e sul altra appare il bottone "back"
Provo a riscolvere

**Comment by feroda** [comment]
un buon lavoro! non capisco però perché nel tuo fork hai aggiunto nuovamente le foto dei partner e non hai usato quelle già caricate. inoltre mancano FabrianoDigital e Makerspace. Io metterei con "item-divider" di ionic:
- coordinamento -> FabrianoDigital
- contenuti, test e moderazione -> Makerspace e Fabricamenti
- foto da fabriano -> Antonio Stopponi, Matteo Mingo, Fabrizio Lampini, Andrea Bevilacqua
- coders -> Luca Ferroni, Dawid Weglarz

che ne pensate?

**Comment by feroda** [comment]
fixed in 09118c6655e4a311
