### ISSUE TITLE
[firefox] Quando un utente aggiunge un augurio l'area della dedica è disallineata

### ISSUE THREAD

**Issue by feroda** [feroda/digitalwishes-ui#9]
Ho provato sia con la proprietà cols, che con le proprietà dei fogli di stile, sia includendola in altri tag html, ma non ci sono riuscito

**Comment by feroda** [comment]
Si verifica su Firefox non su chromium

**Comment by Radeox** [comment]
Credo di aver risolto
![screenshot from 2015-12-29 21-12-11](https://cloud.githubusercontent.com/assets/9751015/12041352/dc551684-ae70-11e5-823b-c68fa5a03e6c.png)

**Comment by feroda** [comment]
fixed in e85376579cb8a9bd
